### ISSUE TITLE
Implementazione Test di unità - Design- Actor

### ISSUE THREAD

**Issue by InnocenteSimone** [fourcatsteam/NaturalAPI#19]
Implementare:

- [ ] - TU19.1
- [ ] - TU19.2
- [ ] - TU19.3
- [x] - TU19.4
- [x] - TU19.5
- [x] - TU19.6
- [ ] - TU19.7

**Comment by GiulioUmbrella** [comment]
Il test TU19.6  prevede che venga restituisce un messaggio di errore se non viene trovata una Action con il nome corrispondete ma viene restituita una lista vuota.
